name: Build Windows Executable

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "latest"

      - name: Set up Python
        run: uv python install 3.13

      - name: Install dependencies
        run: uv sync

      - name: Build executable
        run: uv run pyinstaller main.spec

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SteamPatcher-Windows-exe
          path: dist/steam_patcher.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: SteamPatcher-Windows-exe
          path: dist

      - name: Create or Update "latest" Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Release
          body: |
            This is the most recent build of the Steam Patcher.
            It is automatically updated on every push to the `main` branch.
          files: dist/steam_patcher.exe
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
